export default {
  "id": "lesson-005",
  "title": "Lesson 5",
  "subtitle": "HACER — Singular Persons",
  "objective": "Express productive actions with the verb HACER in the singular persons.",
  "vocabulary": [
    { "id": "trabajo", "emoji": "💼", "noun": "trabajo", "gender": "m", "definite": "el trabajo", "enDefinite": "the work" },
    { "id": "comida", "emoji": "🍽️", "noun": "comida", "gender": "f", "definite": "la comida", "enDefinite": "the meal" },
    { "id": "ejercicio", "emoji": "🏋️", "noun": "ejercicio", "gender": "m", "definite": "el ejercicio", "enDefinite": "the exercise" },
    { "id": "pregunta", "emoji": "❓", "noun": "pregunta", "gender": "f", "definite": "la pregunta", "enDefinite": "the question" },
    { "id": "llamada", "emoji": "📞", "noun": "llamada", "gender": "f", "definite": "la llamada", "enDefinite": "the call" },
    { "id": "tarea", "emoji": "📝", "noun": "tarea", "gender": "f", "definite": "la tarea", "enDefinite": "the task" },
    { "id": "cafe_bebida", "emoji": "☕", "noun": "café", "gender": "m", "definite": "el café", "enDefinite": "the coffee" },
    { "id": "compra", "emoji": "🛒", "noun": "compra", "gender": "f", "definite": "la compra", "enDefinite": "the purchase" }
  ],
  "verbs": [
    { "spanish": "hacer", "english": "to do / to make" }
  ],
  "examples": [
    {
      "title": "HACER — Affirmative",
      "accent": "granate",
      "rows": [
        ["Yo hago el trabajo.", "I do the work."],
        ["Tú haces el trabajo.", "You do the work."],
        ["Él hace el trabajo.", "He does the work."],
        ["Ella hace el trabajo.", "She does the work."],
        ["Yo hago la comida.", "I make the meal."],
        ["Tú haces la comida.", "You make the meal."],
        ["Él hace la comida.", "He makes the meal."],
        ["Ella hace la comida.", "She makes the meal."],
        ["Yo hago ejercicio.", "I exercise."],
        ["Tú haces ejercicio.", "You exercise."],
        ["Él hace ejercicio.", "He exercises."],
        ["Ella hace ejercicio.", "She exercises."],
        ["Yo hago la pregunta.", "I ask the question."],
        ["Tú haces la pregunta.", "You ask the question."],
        ["Él hace la pregunta.", "He asks the question."],
        ["Ella hace la pregunta.", "She asks the question."],
        ["Yo hago la llamada.", "I make the call."],
        ["Tú haces la llamada.", "You make the call."],
        ["Él hace la llamada.", "He makes the call."],
        ["Ella hace la llamada.", "She makes the call."],
        ["Yo hago la tarea.", "I do the task."],
        ["Tú haces la tarea.", "You do the task."],
        ["Él hace la tarea.", "He does the task."],
        ["Ella hace la tarea.", "She does the task."],
        ["Yo hago el café.", "I make the coffee."],
        ["Tú haces el café.", "You make the coffee."],
        ["Él hace el café.", "He makes the coffee."],
        ["Ella hace el café.", "She makes the coffee."],
        ["Yo hago la compra.", "I do the shopping."],
        ["Tú haces la compra.", "You do the shopping."],
        ["Él hace la compra.", "He does the shopping."],
        ["Ella hace la compra.", "She does the shopping."]
      ]
    },
    {
      "title": "HACER — Negative",
      "accent": "carbon",
      "rows": [
        ["Yo no hago el trabajo.", "I don't do the work."],
        ["Tú no haces el trabajo.", "You don't do the work."],
        ["Él no hace el trabajo.", "He doesn't do the work."],
        ["Ella no hace el trabajo.", "She doesn't do the work."],
        ["Yo no hago la comida.", "I don't make the meal."],
        ["Tú no haces la comida.", "You don't make the meal."],
        ["Él no hace la comida.", "He doesn't make the meal."],
        ["Ella no hace la comida.", "She doesn't make the meal."],
        ["Yo no hago ejercicio.", "I don't exercise."],
        ["Tú no haces ejercicio.", "You don't exercise."],
        ["Él no hace ejercicio.", "He doesn't exercise."],
        ["Ella no hace ejercicio.", "She doesn't exercise."],
        ["Yo no hago la pregunta.", "I don't ask the question."],
        ["Tú no haces la pregunta.", "You don't ask the question."],
        ["Él no hace la pregunta.", "He doesn't ask the question."],
        ["Ella no hace la pregunta.", "She doesn't ask the question."],
        ["Yo no hago la llamada.", "I don't make the call."],
        ["Tú no haces la llamada.", "You don't make the call."],
        ["Él no hace la llamada.", "He doesn't make the call."],
        ["Ella no hace la llamada.", "She doesn't make the call."],
        ["Yo no hago la tarea.", "I don't do the task."],
        ["Tú no haces la tarea.", "You don't do the task."],
        ["Él no hace la tarea.", "He doesn't do the task."],
        ["Ella no hace la tarea.", "She doesn't do the task."],
        ["Yo no hago el café.", "I don't make the coffee."],
        ["Tú no haces el café.", "You don't make the coffee."],
        ["Él no hace el café.", "He doesn't make the coffee."],
        ["Ella no hace el café.", "She doesn't make the coffee."],
        ["Yo no hago la compra.", "I don't do the shopping."],
        ["Tú no haces la compra.", "You don't do the shopping."],
        ["Él no hace la compra.", "He doesn't do the shopping."],
        ["Ella no hace la compra.", "She doesn't do the shopping."]
      ]
    },
    {
      "title": "HACER — Questions",
      "accent": "mostaza",
      "rows": [
        ["¿Haces el trabajo?", "Do you do the work?"],
        ["¿Hace el trabajo? (m)", "Does he do the work?"],
        ["¿Hace el trabajo? (f)", "Does she do the work?"],
        ["¿Haces la comida?", "Do you make the meal?"],
        ["¿Hace la comida? (m)", "Does he make the meal?"],
        ["¿Hace la comida? (f)", "Does she make the meal?"],
        ["¿Haces ejercicio?", "Do you exercise?"],
        ["¿Hace ejercicio? (m)", "Does he exercise?"],
        ["¿Hace ejercicio? (f)", "Does she exercise?"],
        ["¿Haces la pregunta?", "Do you ask the question?"],
        ["¿Hace la pregunta? (m)", "Does he ask the question?"],
        ["¿Hace la pregunta? (f)", "Does she ask the question?"],
        ["¿Haces la llamada?", "Do you make the call?"],
        ["¿Hace la llamada? (m)", "Does he make the call?"],
        ["¿Hace la llamada? (f)", "Does she make the call?"],
        ["¿Haces la tarea?", "Do you do the task?"],
        ["¿Hace la tarea? (m)", "Does he do the task?"],
        ["¿Hace la tarea? (f)", "Does she do the task?"],
        ["¿Haces el café?", "Do you make the coffee?"],
        ["¿Hace el café? (m)", "Does he make the coffee?"],
        ["¿Hace el café? (f)", "Does she make the coffee?"],
        ["¿Haces la compra?", "Do you do the shopping?"],
        ["¿Hace la compra? (m)", "Does he do the shopping?"],
        ["¿Hace la compra? (f)", "Does she do the shopping?"]
      ]
    }
  ],
  "drillPatterns": [],
  "finalGym": [
    ["I do the work.", "Yo hago el trabajo."],
    ["You do the work.", "Tú haces el trabajo."],
    ["He does the work.", "Él hace el trabajo."],
    ["She does the work.", "Ella hace el trabajo."],
    ["I don't do the work.", "Yo no hago el trabajo."],
    ["You don't do the work.", "Tú no haces el trabajo."],
    ["He doesn't do the work.", "Él no hace el trabajo."],
    ["She doesn't do the work.", "Ella no hace el trabajo."],
    ["Do you do the work?", "¿Haces el trabajo?"],
    ["Does he do the work?", "¿Hace el trabajo? (m)"],
    ["Does she do the work?", "¿Hace el trabajo? (f)"],
    ["I make the meal.", "Yo hago la comida."],
    ["You make the meal.", "Tú haces la comida."],
    ["He makes the meal.", "Él hace la comida."],
    ["She makes the meal.", "Ella hace la comida."],
    ["I don't make the meal.", "Yo no hago la comida."],
    ["You don't make the meal.", "Tú no haces la comida."],
    ["He doesn't make the meal.", "Él no hace la comida."],
    ["She doesn't make the meal.", "Ella no hace la comida."],
    ["Do you make the meal?", "¿Haces la comida?"],
    ["Does he make the meal?", "¿Hace la comida? (m)"],
    ["Does she make the meal?", "¿Hace la comida? (f)"],
    ["I exercise.", "Yo hago ejercicio."],
    ["You exercise.", "Tú haces ejercicio."],
    ["He exercises.", "Él hace ejercicio."],
    ["She exercises.", "Ella hace ejercicio."],
    ["I don't exercise.", "Yo no hago ejercicio."],
    ["You don't exercise.", "Tú no haces ejercicio."],
    ["He doesn't exercise.", "Él no hace ejercicio."],
    ["She doesn't exercise.", "Ella no hace ejercicio."],
    ["Do you exercise?", "¿Haces ejercicio?"],
    ["Does he exercise?", "¿Hace ejercicio? (m)"],
    ["Does she exercise?", "¿Hace ejercicio? (f)"],
    ["I make the call.", "Yo hago la llamada."],
    ["You make the call.", "Tú haces la llamada."],
    ["He makes the call.", "Él hace la llamada."],
    ["She makes the call.", "Ella hace la llamada."],
    ["I don't make the call.", "Yo no hago la llamada."],
    ["You don't make the call.", "Tú no haces la llamada."],
    ["He doesn't make the call.", "Él no hace la llamada."],
    ["She doesn't make the call.", "Ella no hace la llamada."],
    ["Do you make the call?", "¿Haces la llamada?"],
    ["Does he make the call?", "¿Hace la llamada? (m)"],
    ["Does she make the call?", "¿Hace la llamada? (f)"],
    ["I make the coffee.", "Yo hago el café."],
    ["You make the coffee.", "Tú haces el café."],
    ["He makes the coffee.", "Él hace el café."],
    ["She makes the coffee.", "Ella hace el café."],
    ["I don't make the coffee.", "Yo no hago el café."],
    ["You don't make the coffee.", "Tú no haces el café."],
    ["He doesn't make the coffee.", "Él no hace el café."],
    ["She doesn't make the coffee.", "Ella no hace el café."],
    ["Do you make the coffee?", "¿Haces el café?"],
    ["Does he make the coffee?", "¿Hace el café? (m)"],
    ["Does she make the coffee?", "¿Hace el café? (f)"],
    ["I do the shopping.", "Yo hago la compra."],
    ["You do the shopping.", "Tú haces la compra."],
    ["He does the shopping.", "Él hace la compra."],
    ["She does the shopping.", "Ella hace la compra."]
  ],
  "possessives": [],
  "grammarNotes": [
    { "title": "HACER (to do / to make) + object", "content": "Hago el trabajo (I do the work). / Haces la comida (You make the meal). / Hace ejercicio (He/She exercises). — HACER is used for productive actions and common collocations." }
  ],
  "dialogues": []
};
