export default {
  "id": "lesson-006",
  "title": "Lesson 6",
  "subtitle": "DECIR — Singular Persons",
  "objective": "Express statements and messages with the verb DECIR in the singular persons.",
  "vocabulary": [
    { "id": "si", "emoji": "✅", "noun": "sí", "gender": "m", "definite": "el sí", "enDefinite": "the yes" },
    { "id": "no", "emoji": "❌", "noun": "no", "gender": "m", "definite": "el no", "enDefinite": "the no" },
    { "id": "verdad", "emoji": "💯", "noun": "verdad", "gender": "f", "definite": "la verdad", "enDefinite": "the truth" },
    { "id": "nombre", "emoji": "📛", "noun": "nombre", "gender": "m", "definite": "el nombre", "enDefinite": "the name" },
    { "id": "direccion", "emoji": "📍", "noun": "dirección", "gender": "f", "definite": "la dirección", "enDefinite": "the address" },
    { "id": "hora", "emoji": "🕐", "noun": "hora", "gender": "f", "definite": "la hora", "enDefinite": "the time" },
    { "id": "precio", "emoji": "💶", "noun": "precio", "gender": "m", "definite": "el precio", "enDefinite": "the price" },
    { "id": "numero", "emoji": "🔢", "noun": "número", "gender": "m", "definite": "el número", "enDefinite": "the number" }
  ],
  "verbs": [
    { "spanish": "decir", "english": "to say / to tell" }
  ],
  "examples": [
    {
      "title": "DECIR — Affirmative",
      "accent": "granate",
      "rows": [
        ["Yo digo sí.", "I say yes."],
        ["Tú dices sí.", "You say yes."],
        ["Él dice sí.", "He says yes."],
        ["Ella dice sí.", "She says yes."],
        ["Yo digo no.", "I say no."],
        ["Tú dices no.", "You say no."],
        ["Él dice no.", "He says no."],
        ["Ella dice no.", "She says no."],
        ["Yo digo la verdad.", "I tell the truth."],
        ["Tú dices la verdad.", "You tell the truth."],
        ["Él dice la verdad.", "He tells the truth."],
        ["Ella dice la verdad.", "She tells the truth."],
        ["Yo digo el nombre.", "I say the name."],
        ["Tú dices el nombre.", "You say the name."],
        ["Él dice el nombre.", "He says the name."],
        ["Ella dice el nombre.", "She says the name."],
        ["Yo digo la dirección.", "I say the address."],
        ["Tú dices la dirección.", "You say the address."],
        ["Él dice la dirección.", "He says the address."],
        ["Ella dice la dirección.", "She says the address."],
        ["Yo digo la hora.", "I say the time."],
        ["Tú dices la hora.", "You say the time."],
        ["Él dice la hora.", "He says the time."],
        ["Ella dice la hora.", "She says the time."],
        ["Yo digo el precio.", "I say the price."],
        ["Tú dices el precio.", "You say the price."],
        ["Él dice el precio.", "He says the price."],
        ["Ella dice el precio.", "She says the price."],
        ["Yo digo el número.", "I say the number."],
        ["Tú dices el número.", "You say the number."],
        ["Él dice el número.", "He says the number."],
        ["Ella dice el número.", "She says the number."]
      ]
    },
    {
      "title": "DECIR — Negative",
      "accent": "carbon",
      "rows": [
        ["Yo no digo sí.", "I don't say yes."],
        ["Tú no dices sí.", "You don't say yes."],
        ["Él no dice sí.", "He doesn't say yes."],
        ["Ella no dice sí.", "She doesn't say yes."],
        ["Yo no digo no.", "I don't say no."],
        ["Tú no dices no.", "You don't say no."],
        ["Él no dice no.", "He doesn't say no."],
        ["Ella no dice no.", "She doesn't say no."],
        ["Yo no digo la verdad.", "I don't tell the truth."],
        ["Tú no dices la verdad.", "You don't tell the truth."],
        ["Él no dice la verdad.", "He doesn't tell the truth."],
        ["Ella no dice la verdad.", "She doesn't tell the truth."],
        ["Yo no digo el nombre.", "I don't say the name."],
        ["Tú no dices el nombre.", "You don't say the name."],
        ["Él no dice el nombre.", "He doesn't say the name."],
        ["Ella no dice el nombre.", "She doesn't say the name."],
        ["Yo no digo la dirección.", "I don't say the address."],
        ["Tú no dices la dirección.", "You don't say the address."],
        ["Él no dice la dirección.", "He doesn't say the address."],
        ["Ella no dice la dirección.", "She doesn't say the address."],
        ["Yo no digo la hora.", "I don't say the time."],
        ["Tú no dices la hora.", "You don't say the time."],
        ["Él no dice la hora.", "He doesn't say the time."],
        ["Ella no dice la hora.", "She doesn't say the time."],
        ["Yo no digo el precio.", "I don't say the price."],
        ["Tú no dices el precio.", "You don't say the price."],
        ["Él no dice el precio.", "He doesn't say the price."],
        ["Ella no dice el precio.", "She doesn't say the price."],
        ["Yo no digo el número.", "I don't say the number."],
        ["Tú no dices el número.", "You don't say the number."],
        ["Él no dice el número.", "He doesn't say the number."],
        ["Ella no dice el número.", "She doesn't say the number."]
      ]
    },
    {
      "title": "DECIR — Questions",
      "accent": "mostaza",
      "rows": [
        ["¿Dices sí?", "Do you say yes?"],
        ["¿Dice sí? (m)", "Does he say yes?"],
        ["¿Dice sí? (f)", "Does she say yes?"],
        ["¿Dices no?", "Do you say no?"],
        ["¿Dice no? (m)", "Does he say no?"],
        ["¿Dice no? (f)", "Does she say no?"],
        ["¿Dices la verdad?", "Do you tell the truth?"],
        ["¿Dice la verdad? (m)", "Does he tell the truth?"],
        ["¿Dice la verdad? (f)", "Does she tell the truth?"],
        ["¿Dices el nombre?", "Do you say the name?"],
        ["¿Dice el nombre? (m)", "Does he say the name?"],
        ["¿Dice el nombre? (f)", "Does she say the name?"],
        ["¿Dices la dirección?", "Do you say the address?"],
        ["¿Dice la dirección? (m)", "Does he say the address?"],
        ["¿Dice la dirección? (f)", "Does she say the address?"],
        ["¿Dices la hora?", "Do you say the time?"],
        ["¿Dice la hora? (m)", "Does he say the time?"],
        ["¿Dice la hora? (f)", "Does she say the time?"],
        ["¿Dices el precio?", "Do you say the price?"],
        ["¿Dice el precio? (m)", "Does he say the price?"],
        ["¿Dice el precio? (f)", "Does she say the price?"],
        ["¿Dices el número?", "Do you say the number?"],
        ["¿Dice el número? (m)", "Does he say the number?"],
        ["¿Dice el número? (f)", "Does she say the number?"]
      ]
    }
  ],
  "drillPatterns": [],
  "finalGym": [
    ["I say yes.", "Yo digo sí."],
    ["You say yes.", "Tú dices sí."],
    ["He says yes.", "Él dice sí."],
    ["She says yes.", "Ella dice sí."],
    ["I don't say yes.", "Yo no digo sí."],
    ["You don't say yes.", "Tú no dices sí."],
    ["He doesn't say yes.", "Él no dice sí."],
    ["She doesn't say yes.", "Ella no dice sí."],
    ["Do you say yes?", "¿Dices sí?"],
    ["Does he say yes?", "¿Dice sí? (m)"],
    ["Does she say yes?", "¿Dice sí? (f)"],
    ["I tell the truth.", "Yo digo la verdad."],
    ["You tell the truth.", "Tú dices la verdad."],
    ["He tells the truth.", "Él dice la verdad."],
    ["She tells the truth.", "Ella dice la verdad."],
    ["I don't tell the truth.", "Yo no digo la verdad."],
    ["You don't tell the truth.", "Tú no dices la verdad."],
    ["He doesn't tell the truth.", "Él no dice la verdad."],
    ["She doesn't tell the truth.", "Ella no dice la verdad."],
    ["Do you tell the truth?", "¿Dices la verdad?"],
    ["Does he tell the truth?", "¿Dice la verdad? (m)"],
    ["Does she tell the truth?", "¿Dice la verdad? (f)"],
    ["I say the name.", "Yo digo el nombre."],
    ["You say the name.", "Tú dices el nombre."],
    ["He says the name.", "Él dice el nombre."],
    ["She says the name.", "Ella dice el nombre."],
    ["I don't say the name.", "Yo no digo el nombre."],
    ["You don't say the name.", "Tú no dices el nombre."],
    ["He doesn't say the name.", "Él no dice el nombre."],
    ["She doesn't say the name.", "Ella no dice el nombre."],
    ["Do you say the name?", "¿Dices el nombre?"],
    ["Does he say the name?", "¿Dice el nombre? (m)"],
    ["Does she say the name?", "¿Dice el nombre? (f)"],
    ["I say the address.", "Yo digo la dirección."],
    ["You say the address.", "Tú dices la dirección."],
    ["He says the address.", "Él dice la dirección."],
    ["She says the address.", "Ella dice la dirección."],
    ["I don't say the address.", "Yo no digo la dirección."],
    ["You don't say the address.", "Tú no dices la dirección."],
    ["He doesn't say the address.", "Él no dice la dirección."],
    ["She doesn't say the address.", "Ella no dice la dirección."],
    ["Do you say the address?", "¿Dices la dirección?"],
    ["Does he say the address?", "¿Dice la dirección? (m)"],
    ["Does she say the address?", "¿Dice la dirección? (f)"],
    ["I say the time.", "Yo digo la hora."],
    ["You say the time.", "Tú dices la hora."],
    ["He says the time.", "Él dice la hora."],
    ["She says the time.", "Ella dice la hora."],
    ["I don't say the time.", "Yo no digo la hora."],
    ["You don't say the time.", "Tú no dices la hora."],
    ["He doesn't say the time.", "Él no dice la hora."],
    ["She doesn't say the time.", "Ella no dice la hora."]
  ],
  "possessives": [],
  "grammarNotes": [
    { "title": "DECIR (to say / to tell) + object", "content": "Digo sí (I say yes). / Dices la verdad (You tell the truth). / Dice el nombre (He/She says the name). — DECIR is used for stating or telling something." }
  ],
  "dialogues": []
};
