export default {
  "id": "lesson-004",
  "title": "Lesson 4",
  "subtitle": "PODER + Infinitivo — Singular Persons",
  "objective": "Express ability and permission with the verb PODER + infinitive in the singular persons.",
  "vocabulary": [
    { "id": "correr", "emoji": "🏃", "noun": "correr", "gender": "-", "definite": "correr", "enDefinite": "to run" },
    { "id": "saltar", "emoji": "🦘", "noun": "saltar", "gender": "-", "definite": "saltar", "enDefinite": "to jump" },
    { "id": "nadar", "emoji": "🏊", "noun": "nadar", "gender": "-", "definite": "nadar", "enDefinite": "to swim" },
    { "id": "conducir", "emoji": "🚗", "noun": "conducir", "gender": "-", "definite": "conducir", "enDefinite": "to drive" },
    { "id": "volar", "emoji": "✈️", "noun": "volar", "gender": "-", "definite": "volar", "enDefinite": "to fly" },
    { "id": "cantar", "emoji": "🎤", "noun": "cantar", "gender": "-", "definite": "cantar", "enDefinite": "to sing" },
    { "id": "bailar", "emoji": "💃", "noun": "bailar", "gender": "-", "definite": "bailar", "enDefinite": "to dance" },
    { "id": "leer", "emoji": "📖", "noun": "leer", "gender": "-", "definite": "leer", "enDefinite": "to read" }
  ],
  "verbs": [
    { "spanish": "poder", "english": "to be able to / can" }
  ],
  "examples": [
    {
      "title": "PODER — Affirmative",
      "accent": "granate",
      "rows": [
        ["Yo puedo correr.", "I can run."],
        ["Tú puedes correr.", "You can run."],
        ["Él puede correr.", "He can run."],
        ["Ella puede correr.", "She can run."],
        ["Yo puedo saltar.", "I can jump."],
        ["Tú puedes saltar.", "You can jump."],
        ["Él puede saltar.", "He can jump."],
        ["Ella puede saltar.", "She can jump."],
        ["Yo puedo nadar.", "I can swim."],
        ["Tú puedes nadar.", "You can swim."],
        ["Él puede nadar.", "He can swim."],
        ["Ella puede nadar.", "She can swim."],
        ["Yo puedo conducir.", "I can drive."],
        ["Tú puedes conducir.", "You can drive."],
        ["Él puede conducir.", "He can drive."],
        ["Ella puede conducir.", "She can drive."],
        ["Yo puedo volar.", "I can fly."],
        ["Tú puedes volar.", "You can fly."],
        ["Él puede volar.", "He can fly."],
        ["Ella puede volar.", "She can fly."],
        ["Yo puedo cantar.", "I can sing."],
        ["Tú puedes cantar.", "You can sing."],
        ["Él puede cantar.", "He can sing."],
        ["Ella puede cantar.", "She can sing."],
        ["Yo puedo bailar.", "I can dance."],
        ["Tú puedes bailar.", "You can dance."],
        ["Él puede bailar.", "He can dance."],
        ["Ella puede bailar.", "She can dance."],
        ["Yo puedo leer.", "I can read."],
        ["Tú puedes leer.", "You can read."],
        ["Él puede leer.", "He can read."],
        ["Ella puede leer.", "She can read."]
      ]
    },
    {
      "title": "PODER — Negative",
      "accent": "carbon",
      "rows": [
        ["Yo no puedo correr.", "I can't run."],
        ["Tú no puedes correr.", "You can't run."],
        ["Él no puede correr.", "He can't run."],
        ["Ella no puede correr.", "She can't run."],
        ["Yo no puedo saltar.", "I can't jump."],
        ["Tú no puedes saltar.", "You can't jump."],
        ["Él no puede saltar.", "He can't jump."],
        ["Ella no puede saltar.", "She can't jump."],
        ["Yo no puedo nadar.", "I can't swim."],
        ["Tú no puedes nadar.", "You can't swim."],
        ["Él no puede nadar.", "He can't swim."],
        ["Ella no puede nadar.", "She can't swim."],
        ["Yo no puedo conducir.", "I can't drive."],
        ["Tú no puedes conducir.", "You can't drive."],
        ["Él no puede conducir.", "He can't drive."],
        ["Ella no puede conducir.", "She can't drive."],
        ["Yo no puedo volar.", "I can't fly."],
        ["Tú no puedes volar.", "You can't fly."],
        ["Él no puede volar.", "He can't fly."],
        ["Ella no puede volar.", "She can't fly."],
        ["Yo no puedo cantar.", "I can't sing."],
        ["Tú no puedes cantar.", "You can't sing."],
        ["Él no puede cantar.", "He can't sing."],
        ["Ella no puede cantar.", "She can't sing."],
        ["Yo no puedo bailar.", "I can't dance."],
        ["Tú no puedes bailar.", "You can't dance."],
        ["Él no puede bailar.", "He can't dance."],
        ["Ella no puede bailar.", "She can't dance."],
        ["Yo no puedo leer.", "I can't read."],
        ["Tú no puedes leer.", "You can't read."],
        ["Él no puede leer.", "He can't read."],
        ["Ella no puede leer.", "She can't read."]
      ]
    },
    {
      "title": "PODER — Questions",
      "accent": "mostaza",
      "rows": [
        ["¿Puedes correr?", "Can you run?"],
        ["¿Puede correr? (m)", "Can he run?"],
        ["¿Puede correr? (f)", "Can she run?"],
        ["¿Puedes saltar?", "Can you jump?"],
        ["¿Puede saltar? (m)", "Can he jump?"],
        ["¿Puede saltar? (f)", "Can she jump?"],
        ["¿Puedes nadar?", "Can you swim?"],
        ["¿Puede nadar? (m)", "Can he swim?"],
        ["¿Puede nadar? (f)", "Can she swim?"],
        ["¿Puedes conducir?", "Can you drive?"],
        ["¿Puede conducir? (m)", "Can he drive?"],
        ["¿Puede conducir? (f)", "Can she drive?"],
        ["¿Puedes volar?", "Can you fly?"],
        ["¿Puede volar? (m)", "Can he fly?"],
        ["¿Puede volar? (f)", "Can she fly?"],
        ["¿Puedes cantar?", "Can you sing?"],
        ["¿Puede cantar? (m)", "Can he sing?"],
        ["¿Puede cantar? (f)", "Can she sing?"],
        ["¿Puedes bailar?", "Can you dance?"],
        ["¿Puede bailar? (m)", "Can he dance?"],
        ["¿Puede bailar? (f)", "Can she dance?"],
        ["¿Puedes leer?", "Can you read?"],
        ["¿Puede leer? (m)", "Can he read?"],
        ["¿Puede leer? (f)", "Can she read?"]
      ]
    }
  ],
  "drillPatterns": [],
  "finalGym": [
    ["I can run.", "Yo puedo correr."],
    ["You can run.", "Tú puedes correr."],
    ["He can run.", "Él puede correr."],
    ["She can run.", "Ella puede correr."],
    ["I can't run.", "Yo no puedo correr."],
    ["You can't run.", "Tú no puedes correr."],
    ["He can't run.", "Él no puede correr."],
    ["She can't run.", "Ella no puede correr."],
    ["Can you run?", "¿Puedes correr?"],
    ["Can he run?", "¿Puede correr? (m)"],
    ["Can she run?", "¿Puede correr? (f)"],
    ["I can jump.", "Yo puedo saltar."],
    ["You can jump.", "Tú puedes saltar."],
    ["He can jump.", "Él puede saltar."],
    ["She can jump.", "Ella puede saltar."],
    ["I can't jump.", "Yo no puedo saltar."],
    ["You can't jump.", "Tú no puedes saltar."],
    ["He can't jump.", "Él no puede saltar."],
    ["She can't jump.", "Ella no puede saltar."],
    ["Can you jump?", "¿Puedes saltar?"],
    ["Can he jump?", "¿Puede saltar? (m)"],
    ["Can she jump?", "¿Puede saltar? (f)"],
    ["I can swim.", "Yo puedo nadar."],
    ["You can swim.", "Tú puedes nadar."],
    ["He can swim.", "Él puede nadar."],
    ["She can swim.", "Ella puede nadar."],
    ["I can't swim.", "Yo no puedo nadar."],
    ["You can't swim.", "Tú no puedes nadar."],
    ["He can't swim.", "Él no puede nadar."],
    ["She can't swim.", "Ella no puede nadar."],
    ["Can you swim?", "¿Puedes nadar?"],
    ["Can he swim?", "¿Puede nadar? (m)"],
    ["Can she swim?", "¿Puede nadar? (f)"],
    ["I can drive.", "Yo puedo conducir."],
    ["You can drive.", "Tú puedes conducir."],
    ["He can drive.", "Él puede conducir."],
    ["She can drive.", "Ella puede conducir."],
    ["I can't drive.", "Yo no puedo conducir."],
    ["You can't drive.", "Tú no puedes conducir."],
    ["He can't drive.", "Él no puede conducir."],
    ["She can't drive.", "Ella no puede conducir."],
    ["Can you drive?", "¿Puedes conducir?"],
    ["Can he drive?", "¿Puede conducir? (m)"],
    ["Can she drive?", "¿Puede conducir? (f)"],
    ["I can fly.", "Yo puedo volar."],
    ["You can fly.", "Tú puedes volar."],
    ["He can fly.", "Él puede volar."],
    ["She can fly.", "Ella puede volar."],
    ["I can't fly.", "Yo no puedo volar."],
    ["You can't fly.", "Tú no puedes volar."],
    ["He can't fly.", "Él no puede volar."],
    ["She can't fly.", "Ella no puede volar."],
    ["Can you fly?", "¿Puedes volar?"],
    ["Can he fly?", "¿Puede volar? (m)"],
    ["Can she fly?", "¿Puede volar? (f)"],
    ["I can sing.", "Yo puedo cantar."],
    ["You can sing.", "Tú puedes cantar."],
    ["He can sing.", "Él puede cantar."],
    ["She can sing.", "Ella puede cantar."],
    ["I can't sing.", "Yo no puedo cantar."],
    ["You can't sing.", "Tú no puedes cantar."],
    ["He can't sing.", "Él no puede cantar."],
    ["She can't sing.", "Ella no puede cantar."],
    ["Can you sing?", "¿Puedes cantar?"]
  ],
  "possessives": [],
  "grammarNotes": [
    { "title": "PODER (can / to be able to) + infinitive", "content": "Puedo correr (I can run). / Puedes nadar (You can swim). / Puede conducir (He/She can drive). — PODER expresses physical ability or permission." }
  ],
  "dialogues": []
};
